#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2co - tzvp harmonic basis - direct-UHF
mult 2
charge 1
harmonic
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis tzvp
scftype direct uhf
enter
EOF
../../bin/gamess << EOF
title
h2co - tzvp harmonic basis - direct-ROHF
mult 2
charge 1
harmonic
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis tzvp
scftype direct
enter
EOF
