#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2co - 3-21g - closed shell SCF
super force
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
enter
EOF
../../bin/gamess << EOF
restart
title
h2co+ - 2b2 - 3-21g - open shell RHF
charge 1
mult 2
bypass
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
enter
EOF
../../bin/gamess << EOF
restart
title
h2co+ - 2b1 - 3-21g - open shell RHF
charge 1
mult 2
bypass
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
vectors 1
swap
7 8
end
enter
EOF
../../bin/gamess << EOF
restart
title
h2co+ - 2b2 - 3-21g - UHF
charge 1
mult 2
bypass
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
scftype uhf
enter
EOF
