#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2co - cc-pvdz harmonic closed shell SCF
harmonic
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis cc-pvdz
enter
EOF
../../bin/gamess << EOF
title
h2co - cc-pvtz harmonic closed shell SCF
harmonic
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis cc-pvtz
enter
EOF
