#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2co - 3-21g  - no skeleton.
super off nosym
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
enter
EOF
../../bin/gamess << EOF
restart
cards casscf
title
h2co - casscf (10e in 9 m.o.)
bypass
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
scftype casscf
config print
fzc 1 to 3
doc 4 to 8
uoc 9 to 12
end
enter 8 9
EOF
cat > CASSEL << EOF
#!/usr/bin/perl
#
# crit is minimum weight of a configuration (including spin paths)
# doc is # extra doubly occupieds compared to CAS
# frz is # extra orbitals frozen compared to CAS
#
\$crit = 0.001;
\$doc = 0;
\$frz = 0;
#
if (\$doc >= \$frz)
  {
   \$doc = \$doc - \$frz;
   \$frz = 0;
  }
else
  {
   \$frz = \$frz - \$doc;
   \$doc = 0;
  }
# 
@lines = <STDIN>;
#
#  gather spin paths
#
for (my \$i=0;\$i <= \$#lines; ++\$i)
 {
  @line = split(/ +/,\$lines[\$i]);
  \$line[3] = \$line[3]*\$line[3];
  for (my \$j=\$i+1;\$j <= \$#lines; ++\$j)
   {
    @linj = split(/ +/,\$lines[\$j]);
    if (\$line[2] == \$linj[2])
      { 
       \$line[3] += \$linj[3]*\$linj[3];
       \$lines[\$j] = '0 0 0 0';
      }
    else {}
   }
  \$lines[\$i] = "\$line[0] \$line[1] \$line[2] \$line[3]\n";
 }
#
#  write configurations
#
print "conf \n";
print "? CASSEL script - reference configurations with weight in CAS > \$crit\n";
print "? extra doc \$doc ; extra freeze \$frz\n";
\$nconf = 0;
\$weight = 0.0;
for (\$i=0;\$i <= \$#lines; ++\$i)
 { 
  @line = split(/ +/,\$lines[\$i]);
  if (\$line[3] >= \$crit)
    { 
     ++\$nconf;
     \$weight += \$line[3];
     @conf = split(//,\$line[2]);
     \$nn = \$#conf;
     if (\$frz > 0)
      {\$nn -= \$frz;}
     else {}
    for (\$j=1;\$j <= \$doc  ; ++\$j)
     { print "2 ";}
    for (\$j=0;\$j <= \$nn; ++\$j)
     { 
       print "\$conf[\$j] ";
     }
     print "\n";
    }
 }
print "? \$nconf CASSEL configurations with weigth \$weight \n";
print "end \n";
EOF
chmod +x CASSEL
./CASSEL < civecs.ascii > conf-ascii
../../bin/gamess << EOF
restart
title
h2co - 3-21g   ci conf cards
super off nosym
bypass scf
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
runtype ci
core
1 to 3 end
direct 10 9 10
%include conf-ascii
vectors 8
enter
EOF
