#!/bin/csh
../../bin/gamess << EOF
title
h2co - tzvp + f + g  harmonic basis 
harmonic
zmatrix angstrom
c
o 1 co
h 1 ch 2 hco
h 1 ch 2 hco 3 180.0
variables
co 1.203
ch 1.099
hco 121.8
end
basis 
tzvp o
tzvp c
tzvp h
f c
1 1.0
f o
1.0 1.0
g c 
1.0 1.0
g o
1.0 1.0
end
scftype direct
enter
EOF
