#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2co <-> h2 + co 1a' ts - 6-31g / SCF 
zmat angs
o
c 1 co
x 2 1.0 1 90.0
x 2 chh 3 ang1 1 180.0
x 4 1.0 2 90.0 3 0.0
x 4 1.0 5 ang2 3 0.0
h 4 xh 6 90.0 2 180.0
h 4 xh 6 90.0 2 0.0
variables
co 1.134  
ang1 43.7 
ang2 57.8  
chh  1.292 
xh 0.664   
end
basis 6-31g
runtyp hessian
enter
EOF
../../bin/gamess << EOF
restart new
title
h2co <-> h2 + co 1a' - 6-31g / optimisation 
zmat angs
o
c 1 co
x 2 1.0 1 90.0
x 2 chh 3 ang1 1 180.0
x 4 1.0 2 90.0 3 0.0
x 4 1.0 5 ang2 3 0.0
h 4 xh 6 90.0 2 180.0
h 4 xh 6 90.0 2 0.0
variables
co 1.134  
ang1 43.7 
ang2 57.8 
chh  1.292 
xh 0.664   
end
basis 6-31g
runtyp saddle fcm
enter
EOF
