#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
hcoh <-> h2co 1a' ts - 6-31g / SCF 
zmat angs
c
o 1 co
h 1 ch1 2 och1
h 1 ch5 2 h5co 3 180.0
variables
och1 56.3  
co   1.27  
ch1  1.22  
ch5  1.10  
h5co 115.8 
end
basis 6-31g
runtyp hessian
enter
EOF
../../bin/gamess << EOF
restart new
title
hcoh <-> h2co 1a' - 6-31g / optimisation
zmat angs
c
o 1 co
h 1 ch1 2 och1
h 1 ch5 2 h5co 3 180.0
variables
och1 56.3  
co   1.27  
ch1  1.22  
ch5  1.10  
h5co 115.8 
end
basis 6-31g
runtyp saddle fcm
enter
EOF
