#!/bin/csh
../../bin/gamess << EOF
title
h2co - 3-21g basis - scf + default 1-e properties
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
runtype scf
property atoms
enter
EOF
