#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2co - 3-21g - mrdci 1m/1r 
super off nosym
zmat angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
runtype ci
mrdci
adapt 
tran
table
select
symmetry 1
spin 1
cntrl 16
singles 1
conf
0 1 2 3 4 5  13  17 18
roots 1
thresh 30 10
ci
diag
extrap 2
enter
EOF
/bin/rm table
