#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2co - tzvp + r(sp) basis - scf prior to rpa calculation
super off nosym
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis 
tzvp o
tzvp c
tzvp h
s o
1.0 0.02
p o
1.0 0.02
end
enter 
EOF
../../bin/gamess << EOF
restart
title
h2co - tzvp + r(sp) basis - conventional rpa calculation
super off nosym
bypass scf
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis 
tzvp o
tzvp c
tzvp h
s o
1.0 0.02
p o
1.0 0.02
end
runtype response rpa
tda
symm 1 1 to 5
symm 2 1 to 5
symm 3 1 to 5
symm 4 1 to 5
analyse
enter
EOF
