#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2co - 3-21g - closed shell startup
zmatrix angstrom
c
o 1 co
h 1 ch 2 hco
h 1 ch 2 hco 3 180.0
variables
co 1.203
ch 1.099
hco 121.8
end
enter
EOF
../../bin/gamess << EOF
restart new
title
h2co+ - 3-21g - geometry optimisation SCF
mult 2
charge 1
zmatrix angstrom
c
o 1 co
h 1 ch 2 hco
h 1 ch 2 hco 3 180.0
variables
co 1.203
ch 1.099
hco 121.8
end
runtype optimize 
enter 
EOF
../../bin/gamess << EOF
restart new
title
h2co+ - 3-21g - fp geometry optimisation frozen core + discarded vmos
mult 2
charge 1
zmatrix angstrom
c
o 1 co
h 1 ch 2 hco
h 1 ch 2 hco 3 180.0
variables
co             1.2408256 hess        .691212
ch             1.0818145 hess        .751037
hco          118.2135930 hess        .674146
end
runtype optimize ci
active
3 to 20 end
core 
1 2 end
direct 11 6 12
conf
2 2 2 2 2 1 
enter
EOF
