#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
setenv table ../../libs/TABLE
../../bin/gamess << EOF
title
h2co+ - 2b2 table-ci 
super off nosym
charge 1
mult 2
zmat angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
runtype ci
mrdci
adapt 
tran
select
symmetry 3
spin 2
cntrl 15
singles 1
conf
1 18   1 2 3 4 5  13  17 
roots 1
thresh 30 10
ci
diag
extrap 2
enter
EOF
