#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
 4 classical waters in dielectric - connolly surface, angs
geom au
  0.0              0.0           0.0  0.0  BQ
end
basis
s bq
1.0 1.0
end
maxcyc 0
react
 field stat pert reac pert
 drfout some
 units angstrom
 external
o   w1      -0.796       1.8306236        2.377272     0.0                 
h   w1       0.398       1.8306236        2.9610073   +0.7580462    
h   w1       0.398       1.8306236        2.9610073   -0.7580462    
group    anal 1
o   w2      -0.796       1.8306236       -2.377272     0.0                 
h   w2       0.398       1.8306236       -2.9610073   +0.7580462     
h   w2       0.398       1.8306236       -2.9610073   -0.7580462     
group    anal 2
o   w3      -0.796      -2.377272         0.0         -1.8306236     
h   w3       0.398      -1.6192258        0.0         -1.2468884     
h   w3       0.398      -3.1353182        0.0         -1.2468884     
group    anal 3
o   w4      -0.796      -2.377272         0.0          1.8306236     
h   w4       0.398      -1.6192258        0.0          1.2468884     
h   w4       0.398      -2.0066089        0.0          2.7126571     
group    anal 4
 end
 dielectric
  solvent water
  connolly spdens 0.5021633
  dielout some
 end
end
enter 1
EOF
