#!/bin/csh -f
../../libs/tcgmsg/ipcv4.0/parallel gamess << EOF
title
h2co - tzvp basis - direct-SCF geom. opt /total energy =  -113.9093208
zmatrix angstrom
c
o 1 co
h 1 ch 2 hco
h 1 ch 2 hco 3 180.0
variables
co 1.203
ch 1.099
hco 121.8
end
basis tzvp
runtype optimize
scftype direct
enter 1
EOF
