#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2co <-> h2 + co 1a' ts - sto3g / SCF  energy = -112.129116385856 au
zmat angs
o
c 1 co
x 2 1.0 1 90.0
x 2 chh 3 ang1 1 180.0
x 4 1.0 2 90.0 3 0.0
x 4 1.0 5 ang2 3 0.0
h 4 xh 6 90.0 2 180.0
h 4 xh 6 90.0 2 0.0
variables
co 1.134  type 3
ang1 43.7  type 3
ang2 57.8  type 3
chh  1.292 type 3
xh 0.664   type 3
end
basis sto3g
runtyp saddle
enter
EOF
../../bin/gamess << EOF
dumpfile ed3 1000
title
h2 + co <-> h2co 1a' ts DFT/BLYP 6-31g /  energy = -114.304128219460 au
zmat angs
o
c 1 co
x 2 1.0 1 90.0
x 2 chh 3 ang1 1 180.0
x 4 1.0 2 90.0 3 0.0
x 4 1.0 5 ang2 3 0.0
h 4 xh 6 90.0 2 180.0
h 4 xh 6 90.0 2 0.0
variables
co 1.134  type 3
ang1 43.7  type 3
ang2 57.8  type 3
chh  1.292 type 3
xh 0.664   type 3
end
basis 6-31g
runtype saddle ed3 1
dft
vectors getq ed3 1 1
enter
EOF
