#!/bin/csh
#QSUB -l mpp_p=16
#QSUB -l mpp_t=2:0:0
#QSUB -lT 2:0:0
#QSUB -eo
#QSUB -r par_2a
cd  ~/GAMESS-UK/examples/t3e
setenv SCACHE_I_STREAMS 1
setenv SCACHE_D_STREAMS 1
time mpprun -n 16 ../../bin/gamess-uk < par_2a.in  > par_2a.out_16
