#!/bin/csh
#QSUB -l mpp_p=4
#QSUB -l mpp_t=2:0:0
#QSUB -lT 2:0:0
#QSUB -eo
#QSUB -r par_7
cd  ~/GAMESS-UK/examples/t3e
setenv SCACHE_I_STREAMS 1
setenv SCACHE_D_STREAMS 1
time mpprun -n 4 ../../bin/gamess-uk < par_7.in  > par_7.out_4
