#!/bin/csh
#QSUB -l mpp_p=128
#QSUB -l mpp_t=2:00:0
#QSUB -lT 2:00:0
#QSUB -eo
#QSUB -r par_41
cd  ~/GAMESS-UK/examples/t3e
setenv SCACHE_I_STREAMS 1
setenv SCACHE_D_STREAMS 1
time mpprun -n 128 ../../bin/gamess-uk < par_41.in  > par_41.out_128
