#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
ethene mixed z-matrix/cartesians -  opt. energy = -77.60098750
zmatrix angstrom
cartesians
c   0.000    0.000    0.000
c   0.000    0.000    cc
h   width    0.000   -depth
internals
h   2  ch  1  cch  3  twist
cartesians
h  -width    0.000   -depth
internals
h   2  ch  1  cch  4  180.0
variables
cc 1.4
ch 1.0
width 0.8
depth 0.5
cch 120.0
twist 10.0
end
runtype optimise
enter
EOF
