#!/bin/csh
../../bin/gamess << EOF
title
h2co - TZVP - harmonic closed shell SCF - aimpac
harmonic
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis tzvp
savefile aimpac file aim001_b.wfn
enter
EOF
