#!/bin/csh
setenv ed1 h2oed1
setenv ed2 h2omain
setenv ed3 h2odump
setenv ed4 h2oed4
setenv ed6 h2oed6
setenv ed9 h2oed9
setenv ed10 h2oed10
../../bin/gamess << EOF
restart scf
title
water 3-21G  casscf / energy -75.6385055 au
zmat angstrom
o
h 1 oh
h 1 oh 2 hoh
variables
oh 0.956
hoh 104.5
end
scftype casscf
config bypass
doc 1 to 5
uoc 6 7
end
superci 1 to 2
newton 3 to 20
hessian 3 to 20
simul 3 to 20
maxcyc 20
vectors 6 7
enter 6 7
EOF
