#!/bin/csh
#QSUB -lT 3000
#QSUB -lF 250MB
#QSUB -lM 2Gb
#QSUB  -eo
#QSUB -s /bin/csh
#QSUB -l mpp_p=8
#
cd /kong/u3/gamess/GAMESS-UK/examples/origin
/kong/u3/gamess/GAMESS-UK/bin/parallel gamess < par_2.in > par_2.out
