/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class libjagentxJNI {
  public final static native int axGetUri(String jarg1);
  public final static native int axDataGetUri(String jarg1);
  public final static native int axSelect(String jarg1);
  public final static native int axSelectNext();
  public final static native int axSelectPrev();
  public final static native int axDeselect();
  public final static native int axBaseUri(String jarg1);
  public final static native int axParserFinish();
  public final static native int axParserStart();
  public final static native int axRefine(String jarg1);
  public final static native int axFormat(int jarg1);
  public final static native int axCurrent();
  public final static native String axValue();
  public final static native int axCache(int jarg1);
  public final static native int axSelectNo(int jarg1);
  public final static native String axAbout(String jarg1);
  public final static native String axSelectValue(String jarg1);
  public final static native int axControl(String jarg1, String jarg2);
  public final static native int axSubstitute(String jarg1, String[] jarg2);
  public final static native int axPath(String jarg1, long jarg2);
  public final static native int axClearErrors();
  public final static native int axPrintErrors();
  public final static native int axSetErrorStream(long jarg1);
  public final static native int axGetError(String[] jarg1);
  public final static native int axGetErrors(long jarg1);
}
