#!/bin/csh -f
echo c10000
diff -br c10000.pun VERIFY
echo c10001
diff -br c10001.pun VERIFY
echo c10002
diff -br c10002.pun VERIFY
echo c10003
diff -br c10003.pun VERIFY
echo c10004
diff -br c10004.pun VERIFY
echo c10005
diff -br c10005.pun VERIFY
