#!/bin/csh
#QSUB -l mpp_p=32
#QSUB -l mpp_t=2:0:0
#QSUB -lT 2:0:0
#QSUB -eo
#QSUB -r par_20
cd  ~/GAMESS-UK/examples/t3e
setenv SCACHE_I_STREAMS 1
setenv SCACHE_D_STREAMS 1
time mpprun -n 32 ../../bin/gamess-uk < par_20.in  > par_20.out_32
