#!/bin/csh
#
# validation for parallel tests
#
(cd ../../utilities;make validate)
setenv GAMESS_VTAB ./t3e.vtab
set path=(../../utilities $path)
validate par_1  LOGS/par_1.out
validate par_2  LOGS/par_2.out
validate par_3  LOGS/par_3.out
validate par_4  LOGS/par_4.out
validate par_4a LOGS/par_4a.out
validate par_5  LOGS/par_5.out
validate par_5a  LOGS/par_5a.out
validate par_6  LOGS/par_6.out
validate par_7  LOGS/par_7.out
validate par_8  LOGS/par_8.out
#
validate par_9  LOGS/par_9.out
validate par_10  LOGS/par_10.out
validate par_11  LOGS/par_11.out
validate par_12  LOGS/par_12.out
validate par_13  LOGS/par_13.out
validate par_14  LOGS/par_14.out
validate par_15  LOGS/par_15.out
#
validate par_16  LOGS/par_16.out
validate par_17  LOGS/par_17.out
validate par_18  LOGS/par_18.out
validate par_19  LOGS/par_19.out
validate par_19_uhf  LOGS/par_19_uhf.out
validate par_20  LOGS/par_20.out
validate par_21  LOGS/par_21.out
validate par_22  LOGS/par_22.out
validate par_23  LOGS/par_23.out
validate par_24  LOGS/par_24.out
validate par_25  LOGS/par_25.out
validate par_26  LOGS/par_26.out
validate par_27  LOGS/par_27.out
validate par_28  LOGS/par_28.out
validate par_29  LOGS/par_29.out
validate par_30  LOGS/par_30.out
validate par_31  LOGS/par_31.out
validate par_32  LOGS/par_32.out
validate par_40  LOGS/par_40.out
validate par_41  LOGS/par_41.out
