#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2o surrounded by 4 class water and dielectric, units aa
nosymm
super off
integral high
geom au
  0.0              0.0           0.0  8.0  O
  1.1031           1.4325        0.0  1.0  H
  1.1031          -1.4325        0.0  1.0  H
end
basis sv 4-31g
runtype scf 
maxcyc 100
scftype rhf
thresh 9 
diis on
adapt off
vectors hcore 
react
 field stat scf reac scf      
 gamdrf 0.5
 qmradi conepol
 clasradi conepol
 clasdisp grouppol
 hbond on
 units angstrom
 external
o   w1      -0.796       1.8306236        2.377272     0.0                 
h   w1       0.398       1.8306236        2.9610073   +0.7580462    
h   w1       0.398       1.8306236        2.9610073   -0.7580462    
group    anal 1
o   w2      -0.796       1.8306236       -2.377272     0.0                 
h   w2       0.398       1.8306236       -2.9610073   +0.7580462     
h   w2       0.398       1.8306236       -2.9610073   -0.7580462     
group    anal 2
o   w3      -0.796      -2.377272         0.0         -1.8306236     
h   w3       0.398      -1.6192258        0.0         -1.2468884     
h   w3       0.398      -3.1353182        0.0         -1.2468884     
group    anal 3
o   w4      -0.796      -2.377272         0.0          1.8306236     
h   w4       0.398      -1.6192258        0.0          1.2468884     
h   w4       0.398      -2.0066089        0.0          2.7126571     
group    anal 4
 end
 dielectr
  solvent water
  dieltyp stat opt
  connolly  mxsurpts 100  rprobe 1.9262046
 end
end
enter 1
EOF
