#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2o surrounded by 4 class water and dielectric, direct ci
adapt off
super on nosym
nosym
integral high
geom au
  0.0              0.0           0.0  8.0  O
  1.1031           1.4325        0.0  1.0  H
  1.1031          -1.4325        0.0  1.0  H
end
basis sv 4-31g
runtype ci        
react
 field stat scf reac scf      
 maxcycci 0
 threshci 0.01
 average
 qmradi conepol
 clasradi conepol
 clasdisp grouppol
 expandcc on
 clasclas nodisp norepn noelst
 qmclrep off
 external
o   w1      -0.000       3.459378         4.492394     0.0                 
h   w1       0.000       3.459378         5.595494    +1.4325       
h   w1       0.000       3.459378         5.595494    -1.4325       
group    anal 1
o   w2      -0.000       3.459378        -4.492394     0.0                 
h   w2       0.000       3.459378        -5.595494    +1.4325        
h   w2       0.000       3.459378        -5.595494    -1.4325        
group    anal 2
o   w3      -0.000      -4.492394         0.0         -3.459378      
h   w3       0.000      -3.059894         0.0         -2.356278      
h   w3       0.000      -5.924894         0.0         -2.356278      
group    anal 3
o   w4      -0.000      -4.492394         0.0          3.459378      
h   w4       0.000      -3.059894         0.0          2.356278      
h   w4       0.000      -3.791924         0.0          5.126180      
group    anal 4
 end
end
direct 10 5 8
conf
2 2 2 2 2 
end
symdet
natorb 10 0 print
enter 1
EOF
