# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.

package libplagentx;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package libplagentxc;
bootstrap libplagentx;
package libplagentx;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package libplagentx;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package libplagentx;

*axGetUri = *libplagentxc::axGetUri;
*axDataGetUri = *libplagentxc::axDataGetUri;
*axSelect = *libplagentxc::axSelect;
*axSelectNext = *libplagentxc::axSelectNext;
*axSelectPrev = *libplagentxc::axSelectPrev;
*axDeselect = *libplagentxc::axDeselect;
*axBaseUri = *libplagentxc::axBaseUri;
*axParserFinish = *libplagentxc::axParserFinish;
*axParserStart = *libplagentxc::axParserStart;
*axRefine = *libplagentxc::axRefine;
*axFormat = *libplagentxc::axFormat;
*axCurrent = *libplagentxc::axCurrent;
*axValue = *libplagentxc::axValue;
*axCache = *libplagentxc::axCache;
*axSelectNo = *libplagentxc::axSelectNo;
*axAbout = *libplagentxc::axAbout;
*axSelectValue = *libplagentxc::axSelectValue;
*axControl = *libplagentxc::axControl;
*axSubstitute = *libplagentxc::axSubstitute;
*axPath = *libplagentxc::axPath;
*axClearErrors = *libplagentxc::axClearErrors;
*axPrintErrors = *libplagentxc::axPrintErrors;
*axSetErrorStream = *libplagentxc::axSetErrorStream;
*axGetError = *libplagentxc::axGetError;
*axGetErrors = *libplagentxc::axGetErrors;

# ------- VARIABLE STUBS --------

package libplagentx;

1;
