#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2co - 3-21g - closed shell SCF/total energy = -113.22138585
super force nosym
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
enter 1
EOF
../../bin/gamess << EOF
restart
title
h2co GVB/1-PP 3-21g (1b1->2b1*)/total energy  -113.261453454
bypass
super force nosym
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
scftype gvb 1
vectors 1
swap
7 8
end
enter 2 3
EOF
