#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2co+ - 2b2 - 3-21g - direct- RHF
charge 1
mult 2
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
scftype direct
enter
EOF
../../bin/gamess << EOF
title
h2co+ - 2b2 - 3-21g - direct- RHF
charge 1
mult 2
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
scftype direct gvb
enter
EOF
../../bin/gamess << EOF
title
h2co+ - 2b2 - 3-21g - direct- RHF
charge 1
mult 2
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
scftype direct 
open 1 1
enter
EOF
