#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2 + co <-> h2co 1a' ts 3-21g basis / SCF 
zmat angs
o
c 1 co
x 2 1.0 1 90.0
x 2 chh 3 ang1 1 180.0
x 4 1.0 2 90.0 3 0.0
x 4 1.0 5 ang2 3 0.0
h 4 xh 6 90.0 2 180.0
h 4 xh 6 90.0 2 0.0
variables
co 1.134  type 3
ang1 43.7  type 3
ang2 57.8  type 3
chh  1.292 type 3
xh 0.664   type 3
end
runtype saddle 
enter
EOF
../../bin/gamess << EOF
restart new
title
h2 + co <-> h2co 1a' ts 3-21g basis / CASSCF 
zmat angs
o
c 1 co
x 2 1.0 1 90.0
x 2 chh 3 ang1 1 180.0
x 4 1.0 2 90.0 3 0.0
x 4 1.0 5 ang2 3 0.0
h 4 xh 6 90.0 2 180.0
h 4 xh 6 90.0 2 0.0
variables
co             1.1525832 type 3
chh            1.2981078 type 3
xh             0.6596229 type 3
ang1          43.4018534 type 3
ang2          57.3815232 type 3
end
runtype saddle
xtol 0.0005
scftype casscf
config
fzc 1 to 3
doc 4 to 8
uoc 9 to 12
end
enter
EOF
