#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
time 0.10
title
h2co - tzvp  closed shell scf  -  suppress skeletonisation
super off nosym
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis tzvp
enter
EOF
../../bin/gamess << EOF
restart scf
title
h2co - tzvp - restart scf 
super off nosym
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis tzvp
enter
EOF
