#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
setenv ed6 mfged6
../../bin/gamess << EOF
title
h2co - 3-21g default basis - closed shell scf - polarizability
zmatrix angstrom
c
o 1 co
h 1 ch 2 hco
h 1 ch 2 hco 3 180.0
variables
co 1.203
ch 1.099
hco 121.8
end
runtype polariza
enter
EOF
