#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
h2co <-> h2 + co 1a' ts - sto3g / SCF 
zmat angs
o
c 1 co
x 2 1.0 1 90.0
x 2 chh 3 ang1 1 180.0
x 4 1.0 2 90.0 3 0.0
x 4 1.0 5 ang2 3 0.0
h 4 xh 6 90.0 2 180.0
h 4 xh 6 90.0 2 0.0
variables
co 1.134  type 3
ang1 43.7  type 3
ang2 57.8  type 3
chh  1.292 type 3
xh 0.664   type 3
end
basis sto3g
runtyp saddle
enter
EOF
../../bin/gamess << EOF
dumpfile ed3 2000
title
h2 + co <-> h2co 1a' ts 3-21g basis / SCF 
zmat angs
o
c 1 co
x 2 1.0 1 90.0
x 2 chh 3 ang1 1 180.0
x 4 1.0 2 90.0 3 0.0
x 4 1.0 5 ang2 3 0.0
h 4 xh 6 90.0 2 180.0
h 4 xh 6 90.0 2 0.0
variables
co 1.134  type 3
ang1 43.7  type 3
ang2 57.8  type 3
chh  1.292 type 3
xh 0.664   type 3
end
runtype saddle ed3 1
vectors getq ed3 1 1
enter
EOF
../../bin/gamess << EOF
time 15
dumpfile ed3 2000
restart
title
h2 + co - h2co ts / w(i) -2211.6 /ZVPE 12.2 
zmat angs
o
c 1 co
x 2 1.0 1 90.0
x 2 chh 3 ang1 1 180.0
x 4 1.0 2 90.0 3 0.0
x 4 1.0 5 ang2 3 0.0
h 4 xh 6 90.0 2 180.0
h 4 xh 6 90.0 2 0.0
variables
co 1.20061  type 3
ang1 36.981  type 3
ang2 68.824  type 3
chh  1.189447 type 3
xh 0.563628 type 3
end
runtype force
enter
EOF
