#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
setenv ed6 mfged6
../../bin/gamess << EOF
title
h2co - tzvp basis - ccsd / ccsd energy = -114.2927620
super off nosym
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis  tzvp
ccsd 
enter 
EOF
../../bin/gamess << EOF
title
h2co - tzvp basis - ccsd(t) / ccsd(t) energy = -114.3054523
super off nosym
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis  tzvp
ccsd(t)
enter 
EOF
