#!/bin/csh
../../bin/gamess << EOF
title
h2co+ 2B2 3-21g - default mrdci settings -113.06510859 
mult 2
charge 1
zmat angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
runtype ci
mrdci direct
enter
EOF
../../bin/gamess << EOF
title
h2co+ 2B2 3-21g - explicit data for defaults -113.06510859 
mult 2
charge 1
super off nosym
zmat angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
runtype ci
open 1 1
active
1 to 22 end
mrdci direct
table
select
cntrl 15
spin 2
symm 3
singles all
conf 
1      18   1   2   3   4   5  13  17
1      18   1   2   3   4   6  13  17
3       5   6  18   1   2   3   4  13  17
3       5   7  18   1   2   3   4  13  17
1      18   1   2   3   4   5  14  17
3      13  14  18   1   2   3   4   5  17
3      13  15  18   1   2   3   4   5  17
1      18   1   2   3   4   5  13  19
3      17  18  19   1   2   3   4   5  13
3      17  18  20   1   2   3   4   5  13
1      19   1   2   3   4   5  13  17
1      20   1   2   3   4   5  13  17
end
thresh 10 10
roots 1
ci
natorb
civec 1
enter
EOF
/bin/rm table
