#!/bin/csh
$EXE << EOF
title 
  twisted ethylen 
punch coor conn norm vibr
zmat angs
c
c 1 1.34
h 2 1.09 1 120.
h 2 1.09 1 120. 3 180.
h 1 1.09 2 120. 3 0.
h 1 1.09 2 120. 3 180.
end
basis sto3g
runtype force
scftype rhf
enter
EOF
