#!/bin/csh
../../bin/gamess << EOF
title
h2co - TZVP - harmonic closed shell CCSD - aimpac - FAILS
harmonic
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis tzvp
runtype ci
active
  1 to 48
end
ccsd 48 8 8
natorb 10 print
savefile aimpac section 10 file aim010_b.wfn
enter
EOF
