#!/bin/csh -f
../../libs/tcgmsg/ipcv4.0/parallel gamess << EOF
title
h2co - TZVP basis - closed shell scf
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis tzvp
enter 1
EOF
