#!/bin/csh -f
../../libs/tcgmsg/ipcv4.0/parallel gamess << EOF
file ed2 mfged2
file ed3 mfged3
title
h2co - 3-21g  - no skeleton./total energy -113.22138585
super off nosym
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
enter 1
EOF
../../libs/tcgmsg/ipcv4.0/parallel gamess << EOF
file ed2 mfged2
file ed3 mfged3
restart
title
h2co - casscf (10e in 9 m.o.)/total energy  -113.35636304
bypass
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
scftype casscf
config print nosort
fzc 1 to 3
doc 4 to 8
uoc 9 to 12
end
superci 1 to 7
newton 8 to 20
hessian 8 to 20
vectors 1
enter 2 3
EOF
