#!/bin/csh -f
../../libs/tcgmsg/ipcv4.0/parallel gamess << EOF
title
h2co - 1a1 - local ecp/total energy = -22.26254177
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis ecpdz
pseudo ecp
o o
c c
enter 1 
EOF
