#!/bin/csh
../../bin/gamess << EOF
TITLE
H2CO - TZVP - EXPLICIT DATA FOR DEFAULT MRDCI SETTINGS
SUPER OFF NOSYM
ZMAT ANGSTROM
C
O 1 1.203
H 1 1.099 2 121.8
H 1 1.099 2 121.8 3 180.0
END
BASIS TZVP
RUNTYPE CI
ACTIVE
1 TO 52 END
MRDCI DIRECT
TABLE
SELECT
CNTRL 16
SPIN 1
SYMM 1
SINGLES ALL
CONF
 0       1   2   3   4   5  28  37  38
 0       1   2   3   4   6  28  37  38
 2       5   6   1   2   3   4  28  37  38
 2       5   7   1   2   3   4  28  37  38
 0       1   2   3   4   5  29  37  38
 2      28  29   1   2   3   4   5  37  38
 2      28  30   1   2   3   4   5  37  38
 0       1   2   3   4   5  28  37  39
 2      38  39   1   2   3   4   5  28  37
 2      38  40   1   2   3   4   5  28  37
END
THRESH 10 10
ROOTS 1
CI
NATORB
CIVEC 1
ENTER
EOF
../../bin/gamess << EOF
TITLE
H2CO+ 2B2 TZVP - EXPLICIT DATA FOR DEFAULTS
MULT 2
CHARGE 1
SUPER OFF NOSYM
ZMAT ANGSTROM
C
O 1 1.203
H 1 1.099 2 121.8
H 1 1.099 2 121.8 3 180.0
END
BASIS TZVP
RUNTYPE CI
OPEN 1 1
ACTIVE
1 TO 52 END
MRDCI DIRECT
TABLE
SELECT
CNTRL 15
SPIN 2
SYMM 3
SINGLES ALL
CONF
 1      38   1   2   3   4   5  28  37  
 1      38   1   2   3   4   6  28  37  
 3       5   6  38   1   2   3   4  28  37  
 3       5   7  38   1   2   3   4  28  37  
 1      38   1   2   3   4   5  29  37  
 3      28  29  38   1   2   3   4   5  37   
 3      28  30  38   1   2   3   4   5  37   
 1      38   1   2   3   4   5  28  39  
 3      37  38  39   1   2   3   4   5  28   
 3      37  38  40   1   2   3   4   5  28   
 1      39   1   2   3   4   5  28  37  
 1      40   1   2   3   4   5  28  37 
END
THRESH 10 10
ROOTS 1
CI
NATORB
CIVEC 1
ENTER
EOF
../../bin/gamess << EOF
TITLE
H2CO+ 2B1 TZVP - EXPLICIT DATA FOR DEFAULTS
MULT 2
CHARGE 1
SUPER OFF NOSYM
ZMAT ANGSTROM
C
O 1 1.203
H 1 1.099 2 121.8
H 1 1.099 2 121.8 3 180.0
END
BASIS TZVP
RUNTYPE CI
OPEN 1 1
ACTIVE
1 TO 52 END
MRDCI DIRECT
TABLE
SELECT
CNTRL 15
SPIN 2
SYMM 2
SINGLES ALL
CONF
 1      28   1   2   3   4   5  37  38  
 1      28   1   2   3   4   6  37  38  
 3       5   6  28   1   2   3   4  37  38  
 3       5   7  28   1   2   3   4  37  38  
 1      28   1   2   3   4   5  37  39  
 3      28  38  39   1   2   3   4   5  37   
 3      28  38  40   1   2   3   4   5  37   
END
THRESH 10 10
ROOTS 1
CI
NATORB
CIVEC 1
SWAP
7 8
END
ENTER 
EOF
