/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class libjagentx {
  public static int axGetUri(String arg0) {
    return libjagentxJNI.axGetUri(arg0);
  }

  public static int axDataGetUri(String arg0) {
    return libjagentxJNI.axDataGetUri(arg0);
  }

  public static int axSelect(String arg0) {
    return libjagentxJNI.axSelect(arg0);
  }

  public static int axSelectNext() {
    return libjagentxJNI.axSelectNext();
  }

  public static int axSelectPrev() {
    return libjagentxJNI.axSelectPrev();
  }

  public static int axDeselect() {
    return libjagentxJNI.axDeselect();
  }

  public static int axBaseUri(String arg0) {
    return libjagentxJNI.axBaseUri(arg0);
  }

  public static int axParserFinish() {
    return libjagentxJNI.axParserFinish();
  }

  public static int axParserStart() {
    return libjagentxJNI.axParserStart();
  }

  public static int axRefine(String arg0) {
    return libjagentxJNI.axRefine(arg0);
  }

  public static int axFormat(int arg0) {
    return libjagentxJNI.axFormat(arg0);
  }

  public static int axCurrent() {
    return libjagentxJNI.axCurrent();
  }

  public static String axValue() {
    return libjagentxJNI.axValue();
  }

  public static int axCache(int arg0) {
    return libjagentxJNI.axCache(arg0);
  }

  public static int axSelectNo(int arg0) {
    return libjagentxJNI.axSelectNo(arg0);
  }

  public static String axAbout(String arg0) {
    return libjagentxJNI.axAbout(arg0);
  }

  public static String axSelectValue(String arg0) {
    return libjagentxJNI.axSelectValue(arg0);
  }

  public static int axControl(String arg0, String arg1) {
    return libjagentxJNI.axControl(arg0, arg1);
  }

  public static int axSubstitute(String arg0, String[] arg1) {
    return libjagentxJNI.axSubstitute(arg0, arg1);
  }

  public static int axPath(String arg0, SWIGTYPE_p_p_p_char values) {
    return libjagentxJNI.axPath(arg0, SWIGTYPE_p_p_p_char.getCPtr(values));
  }

  public static int axClearErrors() {
    return libjagentxJNI.axClearErrors();
  }

  public static int axPrintErrors() {
    return libjagentxJNI.axPrintErrors();
  }

  public static int axSetErrorStream(SWIGTYPE_p_FILE arg0) {
    return libjagentxJNI.axSetErrorStream(SWIGTYPE_p_FILE.getCPtr(arg0));
  }

  public static int axGetError(String[] errorString) {
    return libjagentxJNI.axGetError(errorString);
  }

  public static int axGetErrors(SWIGTYPE_p_p_p_char errorStrings) {
    return libjagentxJNI.axGetErrors(SWIGTYPE_p_p_p_char.getCPtr(errorStrings));
  }

}
