#!/bin/csh
../../bin/gamess << EOF
title
h2co - 6-31g -  direct-DFT/HCTH geometry opt. -  energy = -114.432413747981 au
zmatrix angstrom
c
o 1 co
h 1 ch 2 hco
h 1 ch 2 hco 3 180.0
variables
co 1.203
ch 1.099
hco 121.8
end
basis 6-31g
runtype optimize
scftype direct
dft hcth
enter
EOF
../../bin/gamess << EOF
title
h2co - 6-31g -  conv. DFT/HCTH geometry opt. -  energy = -114.432413748069 au
zmatrix angstrom
c
o 1 co
h 1 ch 2 hco
h 1 ch 2 hco 3 180.0
variables
co 1.203
ch 1.099
hco 121.8
end
basis 6-31g
runtype optimize
dft hcth
enter
EOF
