#!/bin/csh
../../bin/gamess << EOF
title
h2co - 6-31G* - DFT/B97 default quadrature / energy = -114.4604801741 au
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis 6-31g*
dft b97
enter
EOF
../../bin/gamess << EOF
title
h2co - 6-31G* - DFT/B97 default quadrature / energy = -114.4604801733 au
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis 6-31g*
scftype direct
dft b97
enter
EOF
../../bin/gamess << EOF
title
h2co - 6-31G** - DFT/B97 default quadrature / energy = -114.4630931003 au
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis 6-31g**
scftype direct
dft b97
enter
EOF
../../bin/gamess << EOF
title
h2co - TZVP - DFT/B97 default quadrature / energy = -114.5063055325 au
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis tzvp
scftype direct
dft b97
enter
EOF
../../bin/gamess << EOF
title
h2co - TZVP+f - DFT/B97 default quadrature / energy = -114.5093213464 au
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis 
tzvp o
tzvp c
tzvp h
f c
1 1.0
f o
1.0 1.0
end
scftype direct
dft b97
enter
EOF
