#!/bin/csh
../../bin/gamess << EOF
title
h2co - 6-31G - DFT/S-VWN default quadrature / energy = -113.5443352913 au
zmatrix angstrom
c
o 1 1.203
h 1 1.099 2 121.8
h 1 1.099 2 121.8 3 180.0
end
basis 6-31g
scftype direct
dft s-vwn
enter
EOF
