#!/bin/csh
../../bin/gamess << EOF
title
hcn 4-31G DFT/B3LYP saddle point / optimised  energy = -93.175608638701 au
zmat angs
c
x 1 1.0
n 1 cn 2 90.0
h 1 ch 2 90.0 3 hcn
variables
cn 1.1484 type 3
ch 1.5960 type 3
hcn 90.0 type 3
end
basis 4-31g
runtype saddle
dft
enter
EOF
#
../../bin/gamess << EOF
title                
hcn/hnc ts. jorgensen-simons/optimised  energy = -93.175608919524 au
zmat angs
c
x 1 1.0
n 1 cn 2 90.0
h 1 ch 2 90.0 3 hcn
variables
cn 1.1484 type 3
ch 1.5960 type 3
hcn 90.0   type 3
end
basis 4-31g
runtype saddle jorgensen 
powell
maxjor 55
recalc off
rfo off
cutoffs
optprint on
xtol 0.0018
dft
enter
EOF
