#!/bin/csh
#
# validation for chap6
#
setenv GAMESS_VTAB ./chap6.vtab
set path=(../../utilities $path)
validate c6000  LOG/c6000.log
validate c6000a  LOG/c6000a.log
validate c6001  LOG/c6001.log
validate c6002  LOG/c6002.log
validate c6003  LOG/c6003.log
validate c6004  LOG/c6004.log
validate c6005  LOG/c6005.log
validate c6006  LOG/c6006.log
validate c6007  LOG/c6007.log
validate c6008  LOG/c6008.log
validate c6009  LOG/c6009.log
validate c6010  LOG/c6010.log
validate c6011  LOG/c6011.log
validate c6012  LOG/c6012.log
validate c6013  LOG/c6013.log
validate c6014  LOG/c6014.log
#
validate c6100  LOG/c6100.log
validate c6100a  LOG/c6100a.log
validate c6100b  LOG/c6100b.log
validate c6101  LOG/c6101.log
validate c6102  LOG/c6102.log
validate c6103  LOG/c6103.log
validate c6104  LOG/c6104.log
validate c6105  LOG/c6105.log
validate c6106  LOG/c6106.log
validate c6107  LOG/c6107.log
validate c6108  LOG/c6108.log
validate c6108a  LOG/c6108a.log
validate c6109  LOG/c6109.log
validate c6110  LOG/c6110.log
validate c6111  LOG/c6111.log
validate c6112  LOG/c6112.log
validate c6113  LOG/c6113.log
validate c6113a  LOG/c6113a.log
validate c6113b  LOG/c6113b.log
validate c6114  LOG/c6114.log
