dnl test file - do no use with gener.m  
define(dlog,``dlog($@)'')dnl
define(dlog10,``dlog10($@)'')dnl
define(dexp,``dexp($@)'')dnl
define(dsqrt,``dsqrt($@)'')dnl
define(datan,``dtan($@)'')dnl
define(datan2,``dtan2($@)'')dnl
define(dsin,``dsin($@)'')dnl
define(dcos,``dcos($@)'')dnl
define(dabs,``dabs($@)'')dnl
define(dmax1,``dmax1($@)'')dnl
define(dmin1,``dmin1($@)'')dnl
define(idint,``idint($@)'')dnl
define(dmod,``dmod($@)'')dnl
define(dfloat,``dfloat($@)'')dnl
define(dsign,``dsign($@)'')dnl
define(zexp,``zexp($@)'')dnl
define(zlog,``zlog($@)'')dnl
define(zlog10,``zlog10($@)'')dnl
define(zsqrt,``zsqrt($@)'')dnl
define(zcos,``zcos($@)'')dnl
define(zsin,``zsin($@)'')dnl
define(dimag,``dimag($@)'')dnl
define(dtan,``dtan($@)'')dnl
define(dasin,``dasin($@)'')dnl
define(dacos,``dacos($@)'')dnl
define(idmax,``idmax($@)'')dnl
define(idamax,``idamax($@)'')dnl
define(ddot,``ddot($@)'')dnl
define(dscal,``dscal($@)'')dnl
define(dswap,``dswap($@)'')dnl
define(dgthr,``dgthr($@)'')dnl
define(dsctr,``dsctr($@)'')dnl
define(dnrm2,``dnrm2($@)'')dnl
define(dsum,``dsum($@)'')dnl
define(dasum,``sdasum($@)'')dnl
define(idmin,``idmin($@)'')dnl
define(idamin,``idamin($@)'')dnl
define(ddoti,``ddoti($@)'')dnl
define(drot,``drot($@)'')dnl
define(daxpy,``daxpy($@)'')dnl
define(dcopy,``dcopy($@)'')dnl
define(vclr,``vclr($@)'')dnl
define(vfill,``vfill($@)'')dnl
define(dand,``dand($@)'')dnl
define(dor,`` dor($@)'' )dnl
define(dxor,``dxor($@)'')dnl
define(vmul,``vmul($@)'')dnl
define(vadd,``vadd($@)'')dnl
define(vsub,``vsub($@)'')dnl
define(vsma,``vsma($@)'')dnl
undefine(`divert')dnl
undefine(`index')dnl
undefine(`shift')dnl
undefine(`include')dnl
undefine(`undivert')dnl
undefine(`divnum')dnl
undefine(`incr')dnl
undefine(`eval')dnl
undefine(`substr')dnl
undefine(`defn')dnl
undefine(`decr')dnl
undefine(`define')dnl
undefine(`len')dnl
undefine(`dlen')dnl
undefine(`unix')dnl
undefine(`open')dnl
undefine(`undefine')dnl
