#!/bin/csh
#
# validation for parallel tests
#
(cd ../../../../utilities;make validate)
setenv GAMESS_VTAB ../validate.vtab
set path=(../../../../utilities $path)
#
date
#
validate HF.Bz_crco3.TZVP               HF.Bz_crco3.TZVP.out
validate HF_props.pyridine              HF_props.pyridine.out
validate HF.cyclo.sto3G                 HF.cyclo.sto3G.out
validate HF.cyclo.3-21G                 HF.cyclo.3-21G.out
validate HF.cyclo.6-31G                 HF.cyclo.6-31G.out
validate HF.cyclo.6-31G-d               HF.cyclo.6-31G-d.out
validate HF.cyclo.6-31G-dp              HF.cyclo.6-31G-dp.out
validate HF.cyclo.DZP                   HF.cyclo.DZP.out
validate HF.valino.sto3G                HF.valino.sto3G.out
validate HF.valino.3-21G                HF.valino.3-21G.out
validate HF.valino.6-31G                HF.valino.6-31G.out
validate HF.valino.6-31G-d              HF.valino.6-31G-d.out
validate HF.valino.6-31G-dp             HF.valino.6-31G-dp.out
validate HF.hf12z-shell4                HF.hf12z-shell4.out
validate HF.siosi7.3975                 HF.siosi7.3975.out
validate HF_grad.CAG.1291               HF_grad.CAG.1291.out
validate HF_opt.fluro_furan.6-311G++2pd HF_opt.fluro_furan.6-311G++2pd.out
validate HF.morphine.6-31G-d            HF.morphine.6-31G-d.out
validate ECP_opt.crno4                  ECP_opt.crno4.out
validate ECP_SBKJC.crno4                ECP_SBKJC.crno4.out
validate HF.morphine.start              HF.morphine.start.out
validate HF.morphine.restart            HF.morphine.restart.out
#
validate DFT.morphine.6-31G-dp         DFT.morphine.6-31G-dp.out
validate DFT.morphine.6-31G-dp_harmonic DFT.morphine.6-31G-dp_harmonic.out
validate DFT.morphine.A2.DZVP          DFT.morphine.A2.DZVP.out
validate DFT.cyclo.6-31G               DFT.cyclo.6-31G.out
validate DFT.cyclo.6-31G-dp            DFT.cyclo.6-31G-dp.out
validate DFT.valino.6-31G              DFT.valino.6-31G.out
validate DFT.valino.A2.DZVP            DFT.valino.A2.DZVP.out
validate DFT.valino.A2.DZVP2           DFT.valino.A2.DZVP2.out
validate DFT.siosi3.347                DFT.siosi3.347.out
validate DFT.siosi4.617                DFT.siosi4.617.out
validate DFT.siosi5.1199               DFT.siosi5.1199.out
validate DFT.siosi6.1687               DFT.siosi6.1687.out
validate DFT.siosi7.3975               DFT.siosi7.3975.out
validate DFT_opt.exti4a1.3-21G         DFT_opt.exti4a1.3-21G.out
validate DFT.Alpha-pinene.6-311g-3dfp  DFT.Alpha-pinene.6-311g-3dfp.out
validate DFT.c20h42.6-31G-d            DFT.c20h42.6-31G-d.out
validate DFT.hf12z-shell4              DFT.hf12z-shell4.out
validate DFT.pcfe.814                  DFT.pcfe.814.out
#
validate UHF.pyridine           UHF.pyridine.out
validate UHF_opt.pyridine       UHF_opt.pyridine.out
validate UHF.morphine.6-31G-d   UHF.morphine.6-31G-d.out
validate UHF.Bz_crco3.TZVP      UHF.Bz_crco3.TZVP.out
validate UKS.pyridine           UKS.pyridine.out
