#!/bin/csh
date
RUN test_1
RUN test_2
RUN test_3
RUN test_4
RUN test_5
RUN test_6
RUN test_7
RUN test_8
RUN test_9
RUN test_10
RUN test_11
RUN test_13
RUN test_14
RUN test_15
RUN test_16
RUN test_18
RUN test_19
RUN test_20
RUN test_21
RUN test_22
RUN test_23
RUN test_24
RUN test_25
date
/bin/rm mfg*
