#!/bin/csh
../../bin/gamess << EOF
core 6000000
title
scf3 - tzvp basis mp2 - energy = -1059.54409096
zmat angstrom
sc
x 1 1.0
f 1 scf 2 90.0
f1 1 scf 2 90.0 3 120.0
f1 1 scf 2 90.0 3 -120.0
variables
scf 1.8823 hess    .818724
end
basis tzvp
runtype optimize
scftype mp2
level 2
enter 1
EOF
