#!/bin/csh
../../bin/gamess << EOF
title 
Methylamine...RHF/3-21G//Pople-Gordon standard geometry
zmatrix angstrom 
C
N   1   CN
H   1   CH   2   tet
H   1   CH   2   tet   3   120.  0
H   1   CH   2   tet   3   240.  0
H   2   NH   1   tet   3    60.  0
H   2   NH   1   tet   3   300.  0
variables
CN        1.47
CH        1.09
NH        1.01
tet     109.4712
end
enter
runtype analysis
nbo
vectors 1 
enter 1
\$nbo  \$end
EOF
