#!/bin/csh
#QSUB -lT 1000
#QSUB -lF 250MB
#QSUB -lM 2Gb
#QSUB  -eo
#QSUB -s /bin/csh
#QSUB -l mpp_p=4
#
cd /kong/u3/gamess/GAMESS-UK/examples/origin
/kong/u3/gamess/GAMESS-UK/bin/parallel gamess < crno4.dat > crno4.out
