#!/bin/csh
setenv ed2 mfged2
setenv ed3 mfged3
../../bin/gamess << EOF
title
hcn  dunning dz + bond(s,p) 
zmat angstrom
c
bq 1 rcn2
x 2 1.0 1 90.0
n 2 rcn2 3 90.0 1 180.0
x 1 1.0 2 90.0 3 0.0
h 1 rch 5 90.0 4 180.0
variables
rcn2 0.580 
rch 1.056 
end
basis
dz h
s bq
1.0 1.0
p bq
1.0 0.7
dz c
dz n
end
runtype optimize
xtol 0.005
minmax 60 2
stepmax 0.1   
value 0.3
enter
EOF
../../bin/gamess << EOF
restart optimize
title
hcn dz + bond(s,p) / optimised energy  = -92.873899291
zmat angstrom
c
bq 1 rcn2
x 2 1.0 1 90.0
n 2 rcn2 3 90.0 1 180.0
x 1 1.0 2 90.0 3 0.0
h 1 rch 5 90.0 4 180.0
variables
rcn2 0.580 
rch 1.056 
end
basis
dz h
s bq
1.0 1.0
p bq
1.0 0.7
dz c
dz n
end
runtype optimize
xtol 0.0005
stepmax 0.2   
value 0.6
enter
EOF
